import { BoardTile, GameCard } from '../types/game';

export const BOARD_TILES: BoardTile[] = [
  // Corner 0: START (Bottom-Right)
  {
    index: 0,
    name: 'START',
    type: 'start',
    description: 'Collect ₹2,000 salary when passing.',
  },
  // Side 1: Bottom (1 to 9) - Right to Left
  {
    index: 1,
    name: 'Guwahati',
    type: 'property',
    details: {
      id: 'guwahati',
      name: 'Guwahati',
      cost: 600,
      rent: 100,
      rent1: 500,
      rent2: 1500,
      rent3: 4500,
      rent4: 8000,
      hotel: 12000,
      mortgage: 300,
      houseCost: 500,
      group: 'brown',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 2,
    name: 'Community Chest',
    type: 'card',
    description: 'Draw a Chest Card.',
  },
  {
    index: 3,
    name: 'Bhubaneshwar',
    type: 'property',
    details: {
      id: 'bhubaneshwar',
      name: 'Bhubaneshwar',
      cost: 600,
      rent: 120,
      rent1: 600,
      rent2: 1800,
      rent3: 5000,
      rent4: 9000,
      hotel: 13000,
      mortgage: 300,
      houseCost: 500,
      group: 'brown',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 4,
    name: 'Income Tax',
    type: 'tax',
    cost: 2000,
    description: 'Pay ₹2,000 Income Tax to Bank.',
  },
  {
    index: 5,
    name: 'Station 1',
    type: 'railway',
    cost: 2000,
    details: {
      id: 'station-1',
      name: 'Station 1',
      cost: 2000,
      rent: 250,
      rent1: 500,
      rent2: 1000,
      rent3: 2000,
      rent4: 2000,
      hotel: 2000,
      mortgage: 1000,
      houseCost: 0,
      group: 'railway',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 6,
    name: 'Chance',
    type: 'card',
    description: 'Draw a Chance Card.',
  },
  {
    index: 7,
    name: 'Panaji',
    type: 'property',
    details: {
      id: 'panaji',
      name: 'Panaji',
      cost: 1000,
      rent: 140,
      rent1: 700,
      rent2: 2000,
      rent3: 5500,
      rent4: 9500,
      hotel: 14000,
      mortgage: 500,
      houseCost: 500,
      group: 'cyan',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 8,
    name: 'Agra',
    type: 'property',
    details: {
      id: 'agra',
      name: 'Agra',
      cost: 1000,
      rent: 140,
      rent1: 700,
      rent2: 2000,
      rent3: 5500,
      rent4: 9500,
      hotel: 14000,
      mortgage: 500,
      houseCost: 500,
      group: 'cyan',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 9,
    name: 'Vadodara',
    type: 'property',
    details: {
      id: 'vadodara',
      name: 'Vadodara',
      cost: 1200,
      rent: 160,
      rent1: 800,
      rent2: 2400,
      rent3: 6000,
      rent4: 10000,
      hotel: 15000,
      mortgage: 600,
      houseCost: 500,
      group: 'cyan',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  // Corner 10: JAIL (Bottom-Left)
  {
    index: 10,
    name: 'Jail / Just Visiting',
    type: 'jail',
    description: 'Just visiting, or locked in jail.',
  },
  // Side 2: Left (11 to 19) - Bottom to Top
  {
    index: 11,
    name: 'Ludhiana',
    type: 'property',
    details: {
      id: 'ludhiana',
      name: 'Ludhiana',
      cost: 1400,
      rent: 180,
      rent1: 900,
      rent2: 2500,
      rent3: 7000,
      rent4: 10500,
      hotel: 16000,
      mortgage: 700,
      houseCost: 1000,
      group: 'pink',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 12,
    name: 'Electric Utility',
    type: 'utility',
    cost: 1500,
    details: {
      id: 'electric-utility',
      name: 'Electric Utility',
      cost: 1500,
      rent: 150,
      rent1: 300,
      rent2: 600,
      rent3: 1200,
      rent4: 1200,
      hotel: 1200,
      mortgage: 750,
      houseCost: 0,
      group: 'utility',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 13,
    name: 'Patna',
    type: 'property',
    details: {
      id: 'patna',
      name: 'Patna',
      cost: 1400,
      rent: 180,
      rent1: 900,
      rent2: 2500,
      rent3: 7000,
      rent4: 10500,
      hotel: 16000,
      mortgage: 700,
      houseCost: 1000,
      group: 'pink',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 14,
    name: 'Bhopal',
    type: 'property',
    details: {
      id: 'bhopal',
      name: 'Bhopal',
      cost: 1600,
      rent: 200,
      rent1: 1000,
      rent2: 3000,
      rent3: 7500,
      rent4: 11000,
      hotel: 17000,
      mortgage: 800,
      houseCost: 1000,
      group: 'pink',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 15,
    name: 'Station 2',
    type: 'railway',
    cost: 2000,
    details: {
      id: 'station-2',
      name: 'Station 2',
      cost: 2000,
      rent: 250,
      rent1: 500,
      rent2: 1000,
      rent3: 2000,
      rent4: 2000,
      hotel: 2000,
      mortgage: 1000,
      houseCost: 0,
      group: 'railway',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 16,
    name: 'Indore',
    type: 'property',
    details: {
      id: 'indore',
      name: 'Indore',
      cost: 1600,
      rent: 220,
      rent1: 1100,
      rent2: 3300,
      rent3: 8000,
      rent4: 11500,
      hotel: 17500,
      mortgage: 800,
      houseCost: 1000,
      group: 'orange',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 17,
    name: 'Community Chest',
    type: 'card',
    description: 'Draw a Chest Card.',
  },
  {
    index: 18,
    name: 'Nagpur',
    type: 'property',
    details: {
      id: 'nagpur',
      name: 'Nagpur',
      cost: 1800,
      rent: 240,
      rent1: 1200,
      rent2: 3600,
      rent3: 8500,
      rent4: 12000,
      hotel: 18000,
      mortgage: 900,
      houseCost: 1000,
      group: 'orange',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 19,
    name: 'Kochi',
    type: 'property',
    details: {
      id: 'kochi',
      name: 'Kochi',
      cost: 2000,
      rent: 260,
      rent1: 1300,
      rent2: 3900,
      rent3: 9000,
      rent4: 12500,
      hotel: 18500,
      mortgage: 1000,
      houseCost: 1000,
      group: 'orange',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  // Corner 20: FREE PARKING (Top-Left)
  {
    index: 20,
    name: 'Free Parking',
    type: 'rest',
    description: 'Rest area, take a break.',
  },
  // Side 3: Top (21 to 29) - Left to Right
  {
    index: 21,
    name: 'Lucknow',
    type: 'property',
    details: {
      id: 'lucknow',
      name: 'Lucknow',
      cost: 2200,
      rent: 280,
      rent1: 1400,
      rent2: 4200,
      rent3: 9500,
      rent4: 13000,
      hotel: 19000,
      mortgage: 1100,
      houseCost: 1500,
      group: 'red',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 22,
    name: 'Chance',
    type: 'card',
    description: 'Draw a Chance Card.',
  },
  {
    index: 23,
    name: 'Chandigarh',
    type: 'property',
    details: {
      id: 'chandigarh',
      name: 'Chandigarh',
      cost: 2200,
      rent: 280,
      rent1: 1400,
      rent2: 4200,
      rent3: 9500,
      rent4: 13000,
      hotel: 19000,
      mortgage: 1100,
      houseCost: 1500,
      group: 'red',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 24,
    name: 'Jaipur',
    type: 'property',
    details: {
      id: 'jaipur',
      name: 'Jaipur',
      cost: 2400,
      rent: 300,
      rent1: 1500,
      rent2: 4500,
      rent3: 10000,
      rent4: 13500,
      hotel: 20000,
      mortgage: 1200,
      houseCost: 1500,
      group: 'red',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 25,
    name: 'Station 3',
    type: 'railway',
    cost: 2000,
    details: {
      id: 'station-3',
      name: 'Station 3',
      cost: 2000,
      rent: 250,
      rent1: 500,
      rent2: 1000,
      rent3: 2000,
      rent4: 2000,
      hotel: 2000,
      mortgage: 1000,
      houseCost: 0,
      group: 'railway',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 26,
    name: 'Pune',
    type: 'property',
    details: {
      id: 'pune',
      name: 'Pune',
      cost: 2600,
      rent: 320,
      rent1: 1600,
      rent2: 4800,
      rent3: 10500,
      rent4: 14000,
      hotel: 21000,
      mortgage: 1300,
      houseCost: 1500,
      group: 'yellow',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 27,
    name: 'Hyderabad',
    type: 'property',
    details: {
      id: 'hyderabad',
      name: 'Hyderabad',
      cost: 2600,
      rent: 320,
      rent1: 1600,
      rent2: 4800,
      rent3: 10500,
      rent4: 14000,
      hotel: 21000,
      mortgage: 1300,
      houseCost: 1500,
      group: 'yellow',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 28,
    name: 'Water Utility',
    type: 'utility',
    cost: 1500,
    details: {
      id: 'water-utility',
      name: 'Water Utility',
      cost: 1500,
      rent: 150,
      rent1: 300,
      rent2: 600,
      rent3: 1200,
      rent4: 1200,
      hotel: 1200,
      mortgage: 750,
      houseCost: 0,
      group: 'utility',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 29,
    name: 'Ahmedabad',
    type: 'property',
    details: {
      id: 'ahmedabad',
      name: 'Ahmedabad',
      cost: 2800,
      rent: 350,
      rent1: 1750,
      rent2: 5000,
      rent3: 11000,
      rent4: 15000,
      hotel: 22000,
      mortgage: 1400,
      houseCost: 1500,
      group: 'yellow',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  // Corner 30: GO TO JAIL (Top-Right)
  {
    index: 30,
    name: 'Go To Jail',
    type: 'go_to_jail',
    description: 'Go directly to Jail. Do not pass GO.',
  },
  // Side 4: Right (31 to 39) - Top to Bottom
  {
    index: 31,
    name: 'Kolkata',
    type: 'property',
    details: {
      id: 'kolkata',
      name: 'Kolkata',
      cost: 3000,
      rent: 380,
      rent1: 1900,
      rent2: 5500,
      rent3: 12000,
      rent4: 16000,
      hotel: 23000,
      mortgage: 1500,
      houseCost: 2000,
      group: 'green',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 32,
    name: 'Chennai',
    type: 'property',
    details: {
      id: 'chennai',
      name: 'Chennai',
      cost: 3000,
      rent: 380,
      rent1: 1900,
      rent2: 5500,
      rent3: 12000,
      rent4: 16000,
      hotel: 23000,
      mortgage: 1500,
      houseCost: 2000,
      group: 'green',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 33,
    name: 'Community Chest',
    type: 'card',
    description: 'Draw a Chest Card.',
  },
  {
    index: 34,
    name: 'Bengaluru',
    type: 'property',
    details: {
      id: 'bengaluru',
      name: 'Bengaluru',
      cost: 3200,
      rent: 400,
      rent1: 2000,
      rent2: 6000,
      rent3: 13000,
      rent4: 17000,
      hotel: 24000,
      mortgage: 1600,
      houseCost: 2000,
      group: 'green',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 35,
    name: 'Station 4',
    type: 'railway',
    cost: 2000,
    details: {
      id: 'station-4',
      name: 'Station 4',
      cost: 2000,
      rent: 250,
      rent1: 500,
      rent2: 1000,
      rent3: 2000,
      rent4: 2000,
      hotel: 2000,
      mortgage: 1000,
      houseCost: 0,
      group: 'railway',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 36,
    name: 'Chance',
    type: 'card',
    description: 'Draw a Chance Card.',
  },
  {
    index: 37,
    name: 'Delhi',
    type: 'property',
    details: {
      id: 'delhi',
      name: 'Delhi',
      cost: 3500,
      rent: 450,
      rent1: 2200,
      rent2: 7000,
      rent3: 15000,
      rent4: 20000,
      hotel: 27000,
      mortgage: 1750,
      houseCost: 2000,
      group: 'blue',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 38,
    name: 'Super Tax',
    type: 'tax',
    cost: 1000,
    description: 'Pay ₹1,000 Super Tax to Bank.',
  },
  {
    index: 39,
    name: 'Mumbai',
    type: 'property',
    details: {
      id: 'mumbai',
      name: 'Mumbai',
      cost: 4000,
      rent: 500,
      rent1: 2500,
      rent2: 8000,
      rent3: 17500,
      rent4: 22000,
      hotel: 30000,
      mortgage: 2000,
      houseCost: 2000,
      group: 'blue',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
];

export const CHANCE_CARDS: GameCard[] = [
  { id: 'c-1', title: 'Advance to START and collect ₹2,000!', deck: 'chance', action: 'move', value: 0 },
  { id: 'c-2', title: 'Speeding fine! Pay ₹500.', deck: 'chance', action: 'money', value: -500 },
  { id: 'c-3', title: 'Bank dividend! Collect ₹1,000.', deck: 'chance', action: 'money', value: 1000 },
  { id: 'c-4', title: 'Go directly to Jail! Do not pass START.', deck: 'chance', action: 'jail', value: 10 },
  { id: 'c-5', title: 'Trip to Mumbai! Advance to Mumbai.', deck: 'chance', action: 'move', value: 39 },
  { id: 'c-6', title: 'Get out of Jail Free card!', deck: 'chance', action: 'jail-release', value: 0 },
];

export const COMMUNITY_CHEST_CARDS: GameCard[] = [
  { id: 'cc-1', title: 'Doctor fee! Pay ₹500.', deck: 'community', action: 'money', value: -500 },
  { id: 'cc-2', title: 'Income tax refund! Collect ₹2,000.', deck: 'community', action: 'money', value: 2000 },
  { id: 'cc-3', title: 'Life insurance matures! Collect ₹1,000.', deck: 'community', action: 'money', value: 1000 },
  { id: 'cc-4', title: 'Hospital bill! Pay ₹1,000.', deck: 'community', action: 'money', value: -1000 },
  { id: 'cc-5', title: 'Grand prize in contest! Collect ₹1,500.', deck: 'community', action: 'money', value: 1500 },
  { id: 'cc-6', title: 'Get out of Jail Free card!', deck: 'community', action: 'jail-release', value: 0 },
];

export const CHANCE_DECK = CHANCE_CARDS;
export const COMMUNITY_DECK = COMMUNITY_CHEST_CARDS;
