import { BoardTile, GameCard } from '../types/game';

export const BOARD_TILES: BoardTile[] = [
  // Corner 0: START (Bottom-Right)
  {
    index: 0,
    name: 'START',
    type: 'start',
    description: 'Collect ₹200 salary when passing.',
  },
  // Side 1: Bottom (1 to 9) - Right to Left
  {
    index: 1,
    name: 'Guwahati',
    type: 'property',
    details: {
      id: 'guwahati',
      name: 'Guwahati',
      cost: 60,
      rent: 10,
      rent1: 50,
      rent2: 150,
      rent3: 450,
      rent4: 800,
      hotel: 1200,
      mortgage: 30,
      houseCost: 50,
      group: 'brown',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 2,
    name: 'Community Chest',
    type: 'card',
    description: 'Draw a Chest Card.',
  },
  {
    index: 3,
    name: 'Bhubaneshwar',
    type: 'property',
    details: {
      id: 'bhubaneshwar',
      name: 'Bhubaneshwar',
      cost: 60,
      rent: 12,
      rent1: 60,
      rent2: 180,
      rent3: 500,
      rent4: 900,
      hotel: 1300,
      mortgage: 30,
      houseCost: 50,
      group: 'brown',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 4,
    name: 'Income Tax',
    type: 'tax',
    cost: 200,
    description: 'Pay ₹200 Income Tax to Bank.',
  },
  {
    index: 5,
    name: 'Station 1',
    type: 'railway',
    cost: 200,
    details: {
      id: 'station-1',
      name: 'Station 1',
      cost: 200,
      rent: 25,
      rent1: 50,
      rent2: 100,
      rent3: 200,
      rent4: 200,
      hotel: 200,
      mortgage: 100,
      houseCost: 0,
      group: 'railway',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 6,
    name: 'Chance',
    type: 'card',
    description: 'Draw a Chance Card.',
  },
  {
    index: 7,
    name: 'Panaji',
    type: 'property',
    details: {
      id: 'panaji',
      name: 'Panaji',
      cost: 100,
      rent: 14,
      rent1: 70,
      rent2: 200,
      rent3: 550,
      rent4: 950,
      hotel: 1400,
      mortgage: 50,
      houseCost: 50,
      group: 'cyan',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 8,
    name: 'Agra',
    type: 'property',
    details: {
      id: 'agra',
      name: 'Agra',
      cost: 100,
      rent: 14,
      rent1: 70,
      rent2: 200,
      rent3: 550,
      rent4: 950,
      hotel: 1400,
      mortgage: 50,
      houseCost: 50,
      group: 'cyan',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 9,
    name: 'Vadodara',
    type: 'property',
    details: {
      id: 'vadodara',
      name: 'Vadodara',
      cost: 120,
      rent: 16,
      rent1: 80,
      rent2: 240,
      rent3: 600,
      rent4: 1000,
      hotel: 1500,
      mortgage: 60,
      houseCost: 50,
      group: 'cyan',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  // Corner 10: JAIL (Bottom-Left)
  {
    index: 10,
    name: 'Jail / Just Visiting',
    type: 'jail',
    description: 'Just visiting, or locked in jail.',
  },
  // Side 2: Left (11 to 19) - Bottom to Top
  {
    index: 11,
    name: 'Ludhiana',
    type: 'property',
    details: {
      id: 'ludhiana',
      name: 'Ludhiana',
      cost: 140,
      rent: 18,
      rent1: 90,
      rent2: 250,
      rent3: 700,
      rent4: 1050,
      hotel: 1600,
      mortgage: 70,
      houseCost: 100,
      group: 'pink',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 12,
    name: 'Electric Utility',
    type: 'utility',
    cost: 150,
    details: {
      id: 'electric-utility',
      name: 'Electric Utility',
      cost: 150,
      rent: 15,
      rent1: 30,
      rent2: 60,
      rent3: 120,
      rent4: 120,
      hotel: 120,
      mortgage: 75,
      houseCost: 0,
      group: 'utility',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 13,
    name: 'Patna',
    type: 'property',
    details: {
      id: 'patna',
      name: 'Patna',
      cost: 140,
      rent: 18,
      rent1: 90,
      rent2: 250,
      rent3: 700,
      rent4: 1050,
      hotel: 1600,
      mortgage: 70,
      houseCost: 100,
      group: 'pink',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 14,
    name: 'Bhopal',
    type: 'property',
    details: {
      id: 'bhopal',
      name: 'Bhopal',
      cost: 160,
      rent: 20,
      rent1: 100,
      rent2: 300,
      rent3: 750,
      rent4: 1100,
      hotel: 1700,
      mortgage: 80,
      houseCost: 100,
      group: 'pink',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 15,
    name: 'Station 2',
    type: 'railway',
    cost: 200,
    details: {
      id: 'station-2',
      name: 'Station 2',
      cost: 200,
      rent: 25,
      rent1: 50,
      rent2: 100,
      rent3: 200,
      rent4: 200,
      hotel: 200,
      mortgage: 100,
      houseCost: 0,
      group: 'railway',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 16,
    name: 'Indore',
    type: 'property',
    details: {
      id: 'indore',
      name: 'Indore',
      cost: 160,
      rent: 22,
      rent1: 110,
      rent2: 330,
      rent3: 800,
      rent4: 1150,
      hotel: 1750,
      mortgage: 80,
      houseCost: 100,
      group: 'orange',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 17,
    name: 'Community Chest',
    type: 'card',
    description: 'Draw a Chest Card.',
  },
  {
    index: 18,
    name: 'Nagpur',
    type: 'property',
    details: {
      id: 'nagpur',
      name: 'Nagpur',
      cost: 180,
      rent: 24,
      rent1: 120,
      rent2: 360,
      rent3: 850,
      rent4: 1200,
      hotel: 1800,
      mortgage: 90,
      houseCost: 100,
      group: 'orange',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 19,
    name: 'Kochi',
    type: 'property',
    details: {
      id: 'kochi',
      name: 'Kochi',
      cost: 200,
      rent: 26,
      rent1: 130,
      rent2: 390,
      rent3: 900,
      rent4: 1250,
      hotel: 1850,
      mortgage: 100,
      houseCost: 100,
      group: 'orange',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  // Corner 20: FREE PARKING (Top-Left)
  {
    index: 20,
    name: 'Free Parking',
    type: 'rest',
    description: 'Rest area, take a break.',
  },
  // Side 3: Top (21 to 29) - Left to Right
  {
    index: 21,
    name: 'Lucknow',
    type: 'property',
    details: {
      id: 'lucknow',
      name: 'Lucknow',
      cost: 220,
      rent: 28,
      rent1: 140,
      rent2: 420,
      rent3: 950,
      rent4: 1300,
      hotel: 1900,
      mortgage: 110,
      houseCost: 150,
      group: 'red',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 22,
    name: 'Chance',
    type: 'card',
    description: 'Draw a Chance Card.',
  },
  {
    index: 23,
    name: 'Chandigarh',
    type: 'property',
    details: {
      id: 'chandigarh',
      name: 'Chandigarh',
      cost: 220,
      rent: 28,
      rent1: 140,
      rent2: 420,
      rent3: 950,
      rent4: 1300,
      hotel: 1900,
      mortgage: 110,
      houseCost: 150,
      group: 'red',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 24,
    name: 'Jaipur',
    type: 'property',
    details: {
      id: 'jaipur',
      name: 'Jaipur',
      cost: 240,
      rent: 30,
      rent1: 150,
      rent2: 450,
      rent3: 1000,
      rent4: 1350,
      hotel: 2000,
      mortgage: 120,
      houseCost: 150,
      group: 'red',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 25,
    name: 'Station 3',
    type: 'railway',
    cost: 200,
    details: {
      id: 'station-3',
      name: 'Station 3',
      cost: 200,
      rent: 25,
      rent1: 50,
      rent2: 100,
      rent3: 200,
      rent4: 200,
      hotel: 200,
      mortgage: 100,
      houseCost: 0,
      group: 'railway',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 26,
    name: 'Pune',
    type: 'property',
    details: {
      id: 'pune',
      name: 'Pune',
      cost: 260,
      rent: 32,
      rent1: 160,
      rent2: 480,
      rent3: 1050,
      rent4: 1400,
      hotel: 2100,
      mortgage: 130,
      houseCost: 150,
      group: 'yellow',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 27,
    name: 'Hyderabad',
    type: 'property',
    details: {
      id: 'hyderabad',
      name: 'Hyderabad',
      cost: 260,
      rent: 32,
      rent1: 160,
      rent2: 480,
      rent3: 1050,
      rent4: 1400,
      hotel: 2100,
      mortgage: 130,
      houseCost: 150,
      group: 'yellow',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 28,
    name: 'Water Utility',
    type: 'utility',
    cost: 150,
    details: {
      id: 'water-utility',
      name: 'Water Utility',
      cost: 150,
      rent: 15,
      rent1: 30,
      rent2: 60,
      rent3: 120,
      rent4: 120,
      hotel: 120,
      mortgage: 75,
      houseCost: 0,
      group: 'utility',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 29,
    name: 'Ahmedabad',
    type: 'property',
    details: {
      id: 'ahmedabad',
      name: 'Ahmedabad',
      cost: 280,
      rent: 35,
      rent1: 175,
      rent2: 500,
      rent3: 1100,
      rent4: 1500,
      hotel: 2200,
      mortgage: 140,
      houseCost: 150,
      group: 'yellow',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  // Corner 30: GO TO JAIL (Top-Right)
  {
    index: 30,
    name: 'Go To Jail',
    type: 'go_to_jail',
    description: 'Go directly to Jail. Do not pass GO.',
  },
  // Side 4: Right (31 to 39) - Top to Bottom
  {
    index: 31,
    name: 'Kolkata',
    type: 'property',
    details: {
      id: 'kolkata',
      name: 'Kolkata',
      cost: 300,
      rent: 38,
      rent1: 190,
      rent2: 550,
      rent3: 1200,
      rent4: 1600,
      hotel: 2300,
      mortgage: 150,
      houseCost: 200,
      group: 'green',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 32,
    name: 'Chennai',
    type: 'property',
    details: {
      id: 'chennai',
      name: 'Chennai',
      cost: 300,
      rent: 38,
      rent1: 190,
      rent2: 550,
      rent3: 1200,
      rent4: 1600,
      hotel: 2300,
      mortgage: 150,
      houseCost: 200,
      group: 'green',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 33,
    name: 'Community Chest',
    type: 'card',
    description: 'Draw a Chest Card.',
  },
  {
    index: 34,
    name: 'Bengaluru',
    type: 'property',
    details: {
      id: 'bengaluru',
      name: 'Bengaluru',
      cost: 320,
      rent: 40,
      rent1: 200,
      rent2: 600,
      rent3: 1300,
      rent4: 1700,
      hotel: 2400,
      mortgage: 160,
      houseCost: 200,
      group: 'green',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 35,
    name: 'Station 4',
    type: 'railway',
    cost: 200,
    details: {
      id: 'station-4',
      name: 'Station 4',
      cost: 200,
      rent: 25,
      rent1: 50,
      rent2: 100,
      rent3: 200,
      rent4: 200,
      hotel: 200,
      mortgage: 100,
      houseCost: 0,
      group: 'railway',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 36,
    name: 'Chance',
    type: 'card',
    description: 'Draw a Chance Card.',
  },
  {
    index: 37,
    name: 'Delhi',
    type: 'property',
    details: {
      id: 'delhi',
      name: 'Delhi',
      cost: 350,
      rent: 45,
      rent1: 220,
      rent2: 700,
      rent3: 1500,
      rent4: 2000,
      hotel: 2700,
      mortgage: 175,
      houseCost: 200,
      group: 'blue',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 38,
    name: 'Super Tax',
    type: 'tax',
    cost: 100,
    description: 'Pay ₹100 Super Tax to Bank.',
  },
  {
    index: 39,
    name: 'Mumbai',
    type: 'property',
    details: {
      id: 'mumbai',
      name: 'Mumbai',
      cost: 400,
      rent: 50,
      rent1: 250,
      rent2: 800,
      rent3: 1750,
      rent4: 2200,
      hotel: 3000,
      mortgage: 200,
      houseCost: 200,
      group: 'blue',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
];

export const CHANCE_CARDS: GameCard[] = [
  { id: 'c-1', title: 'Advance to START and collect ₹200!', deck: 'chance', action: 'move', value: 0 },
  { id: 'c-2', title: 'Speeding fine! Pay ₹50.', deck: 'chance', action: 'money', value: -50 },
  { id: 'c-3', title: 'Bank dividend! Collect ₹100.', deck: 'chance', action: 'money', value: 100 },
  { id: 'c-4', title: 'Go directly to Jail! Do not pass START.', deck: 'chance', action: 'jail', value: 10 },
  { id: 'c-5', title: 'Trip to Mumbai! Advance to Mumbai.', deck: 'chance', action: 'move', value: 39 },
  { id: 'c-6', title: 'Get out of Jail Free card!', deck: 'chance', action: 'jail-release', value: 0 },
];

export const COMMUNITY_CHEST_CARDS: GameCard[] = [
  { id: 'cc-1', title: 'Doctor fee! Pay ₹50.', deck: 'community', action: 'money', value: -50 },
  { id: 'cc-2', title: 'Income tax refund! Collect ₹200.', deck: 'community', action: 'money', value: 200 },
  { id: 'cc-3', title: 'Life insurance matures! Collect ₹100.', deck: 'community', action: 'money', value: 100 },
  { id: 'cc-4', title: 'Hospital bill! Pay ₹100.', deck: 'community', action: 'money', value: -100 },
  { id: 'cc-5', title: 'Grand prize in contest! Collect ₹150.', deck: 'community', action: 'money', value: 150 },
  { id: 'cc-6', title: 'Get out of Jail Free card!', deck: 'community', action: 'jail-release', value: 0 },
];

export const CHANCE_DECK = CHANCE_CARDS;
export const COMMUNITY_DECK = COMMUNITY_CHEST_CARDS;
