import { BoardTile, GameCard } from '../types/game';

export const BOARD_TILES: BoardTile[] = [
  // Corner 0: START
  {
    index: 0,
    name: 'START',
    type: 'start',
    description: 'Collect ₹2,000 salary when passing.',
  },
  // Side 1: Top (1 to 9)
  {
    index: 1,
    name: 'Guwahati',
    type: 'property',
    details: {
      id: 'guwahati',
      name: 'Guwahati',
      cost: 600,
      rent: 50,
      rent1: 250,
      rent2: 750,
      rent3: 2250,
      rent4: 4000,
      hotel: 6000,
      mortgage: 300,
      houseCost: 500,
      group: 'brown',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 2,
    name: 'Vyapaar Card',
    type: 'card',
    description: 'Draw a Vyapaar Card.',
  },
  {
    index: 3,
    name: 'Bhubaneshwar',
    type: 'property',
    details: {
      id: 'bhubaneshwar',
      name: 'Bhubaneshwar',
      cost: 800,
      rent: 60,
      rent1: 300,
      rent2: 900,
      rent3: 2700,
      rent4: 4500,
      hotel: 6500,
      mortgage: 400,
      houseCost: 500,
      group: 'brown',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 4,
    name: 'Income Tax',
    type: 'tax',
    cost: 1500,
    description: 'Pay ₹1,500 to the Bank.',
  },
  {
    index: 5,
    name: 'Western Railway',
    type: 'railway',
    cost: 2000,
    details: {
      id: 'railway-west',
      name: 'Western Railway',
      cost: 2000,
      rent: 250,
      rent1: 500,
      rent2: 1000,
      rent3: 2000,
      rent4: 2000,
      hotel: 2000,
      mortgage: 1000,
      houseCost: 0,
      group: 'railway',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 6,
    name: 'Kochi',
    type: 'property',
    details: {
      id: 'kochi',
      name: 'Kochi',
      cost: 1000,
      rent: 80,
      rent1: 400,
      rent2: 1000,
      rent3: 3000,
      rent4: 5000,
      hotel: 7500,
      mortgage: 500,
      houseCost: 500,
      group: 'cyan',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 7,
    name: 'Chance',
    type: 'card',
    description: 'Draw a Chance Card.',
  },
  {
    index: 8,
    name: 'Panaji',
    type: 'property',
    details: {
      id: 'panaji',
      name: 'Panaji',
      cost: 1000,
      rent: 80,
      rent1: 400,
      rent2: 1000,
      rent3: 3000,
      rent4: 5000,
      hotel: 7500,
      mortgage: 500,
      houseCost: 500,
      group: 'cyan',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 9,
    name: 'Ludhiana',
    type: 'property',
    details: {
      id: 'ludhiana',
      name: 'Ludhiana',
      cost: 1200,
      rent: 100,
      rent1: 500,
      rent2: 1200,
      rent3: 3600,
      rent4: 6000,
      hotel: 9000,
      mortgage: 600,
      houseCost: 500,
      group: 'cyan',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },

  // Corner 1: JAIL
  {
    index: 10,
    name: 'JAIL',
    type: 'jail',
    description: 'Just visiting, or locked in for fine.',
  },
  // Side 2: Right (11 to 19)
  {
    index: 11,
    name: 'Indore',
    type: 'property',
    details: {
      id: 'indore',
      name: 'Indore',
      cost: 1400,
      rent: 120,
      rent1: 600,
      rent2: 1500,
      rent3: 4500,
      rent4: 7500,
      hotel: 10000,
      mortgage: 700,
      houseCost: 1000,
      group: 'pink',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 12,
    name: 'Electric Co.',
    type: 'utility',
    cost: 1500,
    details: {
      id: 'utility-electric',
      name: 'Electric Co.',
      cost: 1500,
      rent: 100, // Multiplier * dice rolled
      rent1: 150,
      rent2: 200,
      rent3: 250,
      rent4: 250,
      hotel: 250,
      mortgage: 750,
      houseCost: 0,
      group: 'utility',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 13,
    name: 'Jaipur',
    type: 'property',
    details: {
      id: 'jaipur',
      name: 'Jaipur',
      cost: 1400,
      rent: 120,
      rent1: 600,
      rent2: 1500,
      rent3: 4500,
      rent4: 7500,
      hotel: 10000,
      mortgage: 700,
      houseCost: 1000,
      group: 'pink',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 14,
    name: 'Lucknow',
    type: 'property',
    details: {
      id: 'lucknow',
      name: 'Lucknow',
      cost: 1600,
      rent: 140,
      rent1: 700,
      rent2: 1700,
      rent3: 5000,
      rent4: 8000,
      hotel: 11000,
      mortgage: 800,
      houseCost: 1000,
      group: 'pink',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 15,
    name: 'Southern Railway',
    type: 'railway',
    cost: 2000,
    details: {
      id: 'railway-south',
      name: 'Southern Railway',
      cost: 2000,
      rent: 250,
      rent1: 500,
      rent2: 1000,
      rent3: 2000,
      rent4: 2000,
      hotel: 2000,
      mortgage: 1000,
      houseCost: 0,
      group: 'railway',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 16,
    name: 'Patna',
    type: 'property',
    details: {
      id: 'patna',
      name: 'Patna',
      cost: 1800,
      rent: 160,
      rent1: 800,
      rent2: 2000,
      rent3: 6000,
      rent4: 9500,
      hotel: 13000,
      mortgage: 900,
      houseCost: 1000,
      group: 'orange',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 17,
    name: 'Community Chest',
    type: 'card',
    description: 'Draw a Community Chest Card.',
  },
  {
    index: 18,
    name: 'Bhopal',
    type: 'property',
    details: {
      id: 'bhopal',
      name: 'Bhopal',
      cost: 1800,
      rent: 160,
      rent1: 800,
      rent2: 2000,
      rent3: 6000,
      rent4: 9500,
      hotel: 13000,
      mortgage: 900,
      houseCost: 1000,
      group: 'orange',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 19,
    name: 'Surat',
    type: 'property',
    details: {
      id: 'surat',
      name: 'Surat',
      cost: 2000,
      rent: 180,
      rent1: 900,
      rent2: 2200,
      rent3: 6500,
      rent4: 10500,
      hotel: 15000,
      mortgage: 1000,
      houseCost: 1000,
      group: 'orange',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },

  // Corner 2: REST HOUSE
  {
    index: 20,
    name: 'REST HOUSE',
    type: 'rest',
    description: 'Take a break! Rest here peacefully.',
  },
  // Side 3: Bottom (21 to 29)
  {
    index: 21,
    name: 'Ahmedabad',
    type: 'property',
    details: {
      id: 'ahmedabad',
      name: 'Ahmedabad',
      cost: 2200,
      rent: 200,
      rent1: 1000,
      rent2: 2500,
      rent3: 7500,
      rent4: 11500,
      hotel: 17000,
      mortgage: 1100,
      houseCost: 1500,
      group: 'red',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 22,
    name: 'Chance',
    type: 'card',
    description: 'Draw a Chance Card.',
  },
  {
    index: 23,
    name: 'Pune',
    type: 'property',
    details: {
      id: 'pune',
      name: 'Pune',
      cost: 2200,
      rent: 200,
      rent1: 1000,
      rent2: 2500,
      rent3: 7500,
      rent4: 11500,
      hotel: 17000,
      mortgage: 1100,
      houseCost: 1500,
      group: 'red',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 24,
    name: 'Vadodara',
    type: 'property',
    details: {
      id: 'vadodara',
      name: 'Vadodara',
      cost: 2400,
      rent: 220,
      rent1: 1100,
      rent2: 2800,
      rent3: 8000,
      rent4: 12000,
      hotel: 18000,
      mortgage: 1200,
      houseCost: 1500,
      group: 'red',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 25,
    name: 'Eastern Railway',
    type: 'railway',
    cost: 2000,
    details: {
      id: 'railway-east',
      name: 'Eastern Railway',
      cost: 2000,
      rent: 250,
      rent1: 500,
      rent2: 1000,
      rent3: 2000,
      rent4: 2000,
      hotel: 2000,
      mortgage: 1000,
      houseCost: 0,
      group: 'railway',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 26,
    name: 'Hyderabad',
    type: 'property',
    details: {
      id: 'hyderabad',
      name: 'Hyderabad',
      cost: 2600,
      rent: 240,
      rent1: 1200,
      rent2: 3000,
      rent3: 9000,
      rent4: 13500,
      hotel: 20000,
      mortgage: 1300,
      houseCost: 1500,
      group: 'yellow',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 27,
    name: 'Bengaluru',
    type: 'property',
    details: {
      id: 'bengaluru',
      name: 'Bengaluru',
      cost: 2600,
      rent: 240,
      rent1: 1200,
      rent2: 3000,
      rent3: 9000,
      rent4: 13500,
      hotel: 20000,
      mortgage: 1300,
      houseCost: 1500,
      group: 'yellow',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 28,
    name: 'Water Works',
    type: 'utility',
    cost: 1500,
    details: {
      id: 'utility-water',
      name: 'Water Works',
      cost: 1500,
      rent: 100, // Multiplier * dice rolled
      rent1: 150,
      rent2: 200,
      rent3: 250,
      rent4: 250,
      hotel: 250,
      mortgage: 750,
      houseCost: 0,
      group: 'utility',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 29,
    name: 'Chennai',
    type: 'property',
    details: {
      id: 'chennai',
      name: 'Chennai',
      cost: 2800,
      rent: 260,
      rent1: 1300,
      rent2: 3300,
      rent3: 9700,
      rent4: 14500,
      hotel: 22000,
      mortgage: 1400,
      houseCost: 1500,
      group: 'yellow',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },

  // Corner 3: GO TO JAIL
  {
    index: 30,
    name: 'GO TO JAIL',
    type: 'go_to_jail',
    description: 'Go directly to Jail. Do not pass START, do not collect salary.',
  },
  // Side 4: Left (31 to 39)
  {
    index: 31,
    name: 'Kolkata',
    type: 'property',
    details: {
      id: 'kolkata',
      name: 'Kolkata',
      cost: 3000,
      rent: 280,
      rent1: 1400,
      rent2: 3600,
      rent3: 10500,
      rent4: 15500,
      hotel: 24000,
      mortgage: 1500,
      houseCost: 2000,
      group: 'green',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 32,
    name: 'Visakhapatnam',
    type: 'property',
    details: {
      id: 'visakhapatnam',
      name: 'Visakhapatnam',
      cost: 3000,
      rent: 280,
      rent1: 1400,
      rent2: 3600,
      rent3: 10500,
      rent4: 15500,
      hotel: 24000,
      mortgage: 1500,
      houseCost: 2000,
      group: 'green',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 33,
    name: 'Community Chest',
    type: 'card',
    description: 'Draw a Community Chest Card.',
  },
  {
    index: 34,
    name: 'Coimbatore',
    type: 'property',
    details: {
      id: 'coimbatore',
      name: 'Coimbatore',
      cost: 3200,
      rent: 300,
      rent1: 1500,
      rent2: 3900,
      rent3: 11000,
      rent4: 16500,
      hotel: 26000,
      mortgage: 1600,
      houseCost: 2000,
      group: 'green',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 35,
    name: 'Northern Railway',
    type: 'railway',
    cost: 2000,
    details: {
      id: 'railway-north',
      name: 'Northern Railway',
      cost: 2000,
      rent: 250,
      rent1: 500,
      rent2: 1000,
      rent3: 2000,
      rent4: 2000,
      hotel: 2000,
      mortgage: 1000,
      houseCost: 0,
      group: 'railway',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 36,
    name: 'Chance',
    type: 'card',
    description: 'Draw a Chance Card.',
  },
  {
    index: 37,
    name: 'Delhi',
    type: 'property',
    details: {
      id: 'delhi',
      name: 'Delhi',
      cost: 3500,
      rent: 350,
      rent1: 1750,
      rent2: 4500,
      rent3: 13000,
      rent4: 18500,
      hotel: 28000,
      mortgage: 1750,
      houseCost: 2000,
      group: 'blue',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
  {
    index: 38,
    name: 'Wealth Tax',
    type: 'tax',
    cost: 1000,
    description: 'Pay ₹1,000 to the Bank.',
  },
  {
    index: 39,
    name: 'Mumbai',
    type: 'property',
    details: {
      id: 'mumbai',
      name: 'Mumbai',
      cost: 4000,
      rent: 400,
      rent1: 2000,
      rent2: 5000,
      rent3: 15000,
      rent4: 21000,
      hotel: 30000,
      mortgage: 2000,
      houseCost: 2000,
      group: 'blue',
      ownerId: null,
      housesCount: 0,
      isMortgaged: false,
    },
  },
];

export const CHANCE_DECK: GameCard[] = [
  { id: 'c1', title: 'Go directly to Jail! Do not pass START.', deck: 'chance', action: 'jail', value: 10 },
  { id: 'c2', title: 'Advance to Mumbai (Index 39).', deck: 'chance', action: 'move', value: 39 },
  { id: 'c3', title: 'Advance to Delhi (Index 37).', deck: 'chance', action: 'move', value: 37 },
  { id: 'c4', title: 'Medical Emergency. Pay ₹1,000.', deck: 'chance', action: 'money', value: -1000 },
  { id: 'c5', title: 'Birthday gift! Collect ₹500 from Bank.', deck: 'chance', action: 'money', value: 500 },
];

export const COMMUNITY_DECK: GameCard[] = [
  { id: 'v1', title: 'Won Lottery! Collect ₹2,000.', deck: 'community', action: 'money', value: 2000 },
  { id: 'v2', title: 'Income Tax refund. Collect ₹1,000.', deck: 'community', action: 'money', value: 1000 },
  { id: 'v3', title: 'Speeding Fine. Pay ₹500.', deck: 'community', action: 'money', value: -500 },
  { id: 'v4', title: 'Shares Dividend. Collect ₹1,500.', deck: 'community', action: 'money', value: 1500 },
  { id: 'v5', title: 'Go directly to REST HOUSE (Index 20).', deck: 'community', action: 'move', value: 20 },
];
